version: "3.8"

services:
  mysql_db:
    image: mysql
    container_name: stock_db
    restart: always
    environment:
      # use secret file for password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_pass_secret
      MYSQL_DATABASE: stocks
    # stocks service rely on this health check
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
    secrets:
      # see secrets below
      - mysql_root_pass_secret
    # according to offical data storage
    volumes:
      # see volumes below
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: mysql_db_ui
    restart: always
    ports:
      - 8000:8080

  mongo:
    build: ./mongodb
    image: stock_mongo
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_root_secret
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password_secret
      MONGO_INITDB_DATABASE: stocks
    secrets:
      - mongo_root_secret
      - mongo_password_secret
    ports:
      - 27017:27017
    volumes:
      # see volumes below
      - confg-db-data:/data/db
      - confg-db-data:/data/configdb

  mongo_express:
    image: mongo-express
    container_name: mongo_db_ui
    restart: always
    ports:
      - 8001:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME_FILE: /run/secrets/mongo_root_secret
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongo_password_secret
      ME_CONFIG_MONGODB_SERVER: mongo
    secrets:
      - mongo_root_secret
      - mongo_password_secret
      - express_root_secret
      - express_password_secret
    depends_on:
      mysql_db:
        condition: service_healthy

  # stocks:
  #   image: stocks
  #   container_name: stocks
  #   restart: always
  #   build: ./stocks
  #   depends_on:
  #     mysql_db:
  #       condition: service_healthy

secrets:
  mysql_root_pass_secret:
    # copy mysql password to container
    file: ./secrets/mysql_root_password.txt
  mongo_root_secret:
    file: ./secrets/mongo_root.txt
  mongo_password_secret:
    file: ./secrets/mongo_password.txt
  express_root_secret:
    file: ./secret/express_root.txt
  express_password_secret:
    file: ./secret/express_password.txt

volumes:
  # create a volume for mysql database
  db-data:
    name: stock_db_storage
  confg-db-data:
    name: mongo_db_storage
