version: "3.8"

services:
  db:
    image: mysql
    container_name: stock_db
    restart: always
    environment:
      # use secret file for password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_DATABASE: stocks
    # stocks service rely on this health check
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
    secrets:
      - mysql_secret
    # according to offical data storage
    volumes:
      # see volumes below
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: db_ui
    restart: always
    ports:
      - 8000:8080

  stocks:
    image: stocks
    container_name: stocks
    restart: always
    build: ./stocks
    depends_on:
      db:
        condition: service_healthy

secrets:
  mysql_secret:
    # copy mysql password to container
    file: ./secrets/mysql_secret.txt

volumes:
  # create a volume for mysql database
  db-data:
    name: stock_db_storage
