version: "3.8"

services:
  # MYSQL database service
  mysql_db:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      # use secret file for password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_pass_secret
      MYSQL_DATABASE: stocks
    # stocks service rely on this health check
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
    secrets:
      # see secrets below
      - mysql_root_pass_secret
    # according to offical data storage
    volumes:
      # see volumes below
      - mysql-db-volume:/var/lib/mysql

  # MYSQL admin GUI service for MYSQL database
  adminer:
    image: adminer
    container_name: mysql_db_ui
    restart: always
    ports:
      - 9000:8080
    depends_on:
      mysql_db:
        condition: service_healthy

  # Mongo database service
  mongo:
    build: ./mongodb
    image: mongo_db
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_root_secret
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password_secret
      MONGO_INITDB_DATABASE: stocks
    secrets:
      - mongo_root_secret
      - mongo_password_secret
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      timeout: 20s
      retries: 10
    ports:
      - 27017:27017
    volumes:
      # see volumes below
      - mongo-db-volume:/data/db
      - mongo-db-volume:/data/configdb

  # Mongo admin GUI service for Mongo database
  mongo_express:
    image: mongo-express
    container_name: mongo_db_ui
    restart: always
    ports:
      - 8001:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME_FILE: /run/secrets/mongo_root_secret
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongo_password_secret
      ME_CONFIG_MONGODB_SERVER: mongo
    secrets:
      - mongo_root_secret
      - mongo_password_secret
      - express_root_secret
      - express_password_secret
    depends_on:
      mongo:
        condition: service_healthy

  # Stock manager service
  stock_manager:
    build:
      context: ./
      dockerfile: ./stock_manager/Dockerfile
    image: stock_manager
    container_name: stock_manager
    restart: always
    depends_on:
      mysql_db:
        condition: service_healthy
      mongo:
        condition: service_healthy

  # Stock backend api service
  stock_api:
    build:
      context: ./
      dockerfile: ./stock_api/Dockerfile
    image: stock_api
    container_name: stock_api
    restart: always
    ports:
      - 8002:8002
    depends_on:
      mysql_db:
        condition: service_healthy
      mongo:
        condition: service_healthy

# Sensitive information for services
# In secrets folder
secrets:
  mysql_root_pass_secret:
    # copy mysql password to container
    file: ./secrets/mysql_root_password.txt
  mongo_root_secret:
    file: ./secrets/mongo_root.txt
  mongo_password_secret:
    file: ./secrets/mongo_password.txt
  express_root_secret:
    file: ./secret/express_root.txt
  express_password_secret:
    file: ./secret/express_password.txt

# Docker's volumes(storages) for services
volumes:
  # create a volume for mysql database
  mysql-db-volume:
    name: mysql_db_storage
  mongo-db-volume:
    name: mongo_db_storage
