version: "3.8"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_DATABASE: stocks
    ports:
      - 3306:3306
    secrets:
      - mysql_secret

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

  stocks:
    image: stocks_processor
    build: ./stocks
    env_file:
      - docker.env
    # variables's value extract from .env file in stocks folder
    environment:
      - HOST=${HOST}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - DATABASE=${DATABASE}
    depends_on:
      - db
      - adminer

secrets:
  mysql_secret:
    file: ./secrets/mysql_secret.txt
