version: "3.8"

services:
  db:
    image: mysql
    container_name: stock_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_DATABASE: stocks
    ports:
      - 3306:3306
    secrets:
      - mysql_secret

  adminer:
    image: adminer
    container_name: db_ui
    restart: always
    ports:
      - 8000:8080

  stocks:
    image: stocks_processor
    container_name: stock
    build: ./stocks
    env_file:
      # env variables's value extracted from docker-db.env file in stocks folder
      - docker-db.env
    depends_on:
      - db
      - adminer

secrets:
  mysql_secret:
    file: ./secrets/mysql_secret.txt
