# -*- coding: utf-8 -*-
"""Yahoo_Stock_Prediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CbA4lXxgG5gIPTFgLEDqNuPylD6Co_HY
"""

from utils.utils import setup_logging
from ingestor.stocks_ingestor import ingest_stocks
import matplotlib.pyplot as plt
import pandas as pd
import os

def setup():
  if not os.path.exists("./logs"):
    os.mkdir("./logs")

  setup_logging("./logs/stock_processor.log")

if __name__ == "__main__":
  setup()
  stocks = ["BTC-USD", "GC=FS", "GC=F"]
  print(ingest_stocks(stock_symbols=stocks))



# stock_data

# stock_data.index = pd.to_datetime(stock_data.index).date
# stock_data = stock_data.rename_axis("Date")
# stock_data

# data = stock_data[["Close"]]
# data = data.rename(columns={"Close": "Price"})
# data

# data["P5"] = data["Price"].rolling(5).mean()
# data["P7"] = data["Price"].rolling(7).mean()
# data.head(15)

# data = data.dropna()
# data